/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.clasesSO.RTOSmaster;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import Modelo.EDD.Lista;
import Modelo.EDD.Nodo;
import Modelo.clasesSO.Proceso;
import raven.tabbed.TabbedPaneCustom;

/**
 *
 * @author joseg
 */
public class Vista_1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_1.class.getName());
    private final RTOSmaster RTOSref;
    private final Lista<Proceso> colaNuevo;
    private javax.swing.JButton btnGenerar20;

    /**
     * Creates new form Vista_1
     */
    public Vista_1(RTOSmaster par0, Lista<Proceso> colaNuevo) {
        this.RTOSref = par0;
        this.colaNuevo = colaNuevo;

  
        initComponents();

        // Actualizar tabla inicialmente
        actualizarTableNuevos();

        if (par0 != null && par0.PSW == 0) {
            // Modo KERNEL
            modoU.setVisible(false);
            modoK.setVisible(true);
            PSWbutton.setText("Modo: KERNEL");
        } else {
            // Modo USUARIO
            modoU.setVisible(true);
            modoK.setVisible(false);
            PSWbutton.setText("Modo: USUARIO");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        GestionCargaTAB = new raven.tabbed.TabbedPaneCustom();
        vistaGCProcesos = new javax.swing.JPanel();
        PSWbutton = new javax.swing.JButton();
        gen20 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        gen1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gen21 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        gen2 = new javax.swing.JButton();
        vistaMemoria = new javax.swing.JPanel();
        vistaMetricas = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TRDtext = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        newStatus = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        readyStatus = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        readySStatus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        runningStatus = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        exitStatus = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        blockedStatus = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputStreamConsole = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        blockedSStatus = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        modoU = new javax.swing.JLabel();
        modoK = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        GestionCargaTAB.setForeground(new java.awt.Color(0, 0, 0));
        GestionCargaTAB.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        GestionCargaTAB.setSelectedColor(new java.awt.Color(0, 153, 0));
        GestionCargaTAB.setUnselectedColor(new java.awt.Color(102, 102, 102));

        vistaGCProcesos.setBackground(new java.awt.Color(204, 204, 204));

        PSWbutton.setText("test");
        PSWbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PSWbuttonMouseClicked(evt);
            }
        });
        PSWbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSWbuttonActionPerformed(evt);
            }
        });

        gen20.setText("Generar");
        gen20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gen20ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Generar tarea de emergencia");

        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("CPU");

        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("E/S");

        gen1.setText("Generar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("El valor \"Bound\" será aleatorio si no se especifica");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Generar 20 procesos aleatorios");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Abrir JSON de procesos");

        gen21.setText("Abrir directorio");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "Round Robin", "SRT", "Prioridad Estática Preemptiva", "EDF" }));

        gen2.setText("INICIAR SIMULACIÓN");

        javax.swing.GroupLayout vistaGCProcesosLayout = new javax.swing.GroupLayout(vistaGCProcesos);
        vistaGCProcesos.setLayout(vistaGCProcesosLayout);
        vistaGCProcesosLayout.setHorizontalGroup(
            vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                        .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                                .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gen20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                                        .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton2)
                                                .addGap(116, 116, 116))
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gen1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vistaGCProcesosLayout.createSequentialGroup()
                                .addComponent(gen2)
                                .addGap(38, 38, 38)))
                        .addComponent(PSWbutton))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(96, 96, 96)
                        .addComponent(gen21)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        vistaGCProcesosLayout.setVerticalGroup(
            vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(gen21))
                        .addGap(18, 18, 18)
                        .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gen20)
                            .addComponent(jLabel11)))
                    .addGroup(vistaGCProcesosLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(PSWbutton)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(gen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(vistaGCProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gen2))
                .addContainerGap(547, Short.MAX_VALUE))
        );

        GestionCargaTAB.addTab("Gestión y carga de procesos", vistaGCProcesos);

        vistaMemoria.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout vistaMemoriaLayout = new javax.swing.GroupLayout(vistaMemoria);
        vistaMemoria.setLayout(vistaMemoriaLayout);
        vistaMemoriaLayout.setHorizontalGroup(
            vistaMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        vistaMemoriaLayout.setVerticalGroup(
            vistaMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );

        GestionCargaTAB.addTab("Memoria", vistaMemoria);

        vistaMetricas.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout vistaMetricasLayout = new javax.swing.GroupLayout(vistaMetricas);
        vistaMetricas.setLayout(vistaMetricasLayout);
        vistaMetricasLayout.setHorizontalGroup(
            vistaMetricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        vistaMetricasLayout.setVerticalGroup(
            vistaMetricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );

        GestionCargaTAB.addTab("Metricas", vistaMetricas);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NEW");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BLOCKED");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 70));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("READY/SUSPENDED");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, 70));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("BLOCKED/SUSPENDED");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, -1, 70));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("READY");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("RUNNING");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        TRDtext.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        TRDtext.setForeground(new java.awt.Color(0, 0, 0));
        TRDtext.setText("TRD=TIEMPO RESTANTE DEADLINE");
        jPanel6.add(TRDtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CONSOLA");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        newStatus.setBackground(new java.awt.Color(204, 204, 204));
        newStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane3.setViewportView(newStatus);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 400, 200));

        readyStatus.setBackground(new java.awt.Color(204, 204, 204));
        readyStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane4.setViewportView(readyStatus);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 400, 200));

        readySStatus.setBackground(new java.awt.Color(204, 204, 204));
        readySStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane5.setViewportView(readySStatus);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 400, 220));

        runningStatus.setBackground(new java.awt.Color(204, 204, 204));
        runningStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane2.setViewportView(runningStatus);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 200));

        exitStatus.setBackground(new java.awt.Color(204, 204, 204));
        exitStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane6.setViewportView(exitStatus);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 390, 220));

        blockedStatus.setBackground(new java.awt.Color(204, 204, 204));
        blockedStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane7.setViewportView(blockedStatus);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 400, 220));

        outputStreamConsole.setColumns(20);
        outputStreamConsole.setRows(5);
        jScrollPane1.setViewportView(outputStreamConsole);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 820, 210));

        blockedSStatus.setBackground(new java.awt.Color(204, 204, 204));
        blockedSStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prioridad", "Nombre", "MAR", "PC", "TRD"
            }
        ));
        jScrollPane8.setViewportView(blockedSStatus);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 400, 220));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("EXIT");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, -1, -1));

        modoU.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        modoU.setForeground(new java.awt.Color(102, 255, 102));
        modoU.setText("MODO: USUARIO");

        modoK.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        modoK.setForeground(new java.awt.Color(255, 102, 102));
        modoK.setText("MODO: KERNEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(GestionCargaTAB, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(modoK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modoU)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GestionCargaTAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modoK)
                            .addComponent(modoU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gen20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gen20ActionPerformed
//    if (RTOSref != null) 
                    RTOSref.xPRand(20, colaNuevo);
                    actualizarTableNuevos();
                    outputStreamConsole.append("[SISTEMA] Se han generado 20 procesos aleatorios adicionales.\n");
    }//GEN-LAST:event_gen20ActionPerformed



    public void actualizarTableNuevos() {
        if (colaNuevo == null)
            return;

        DefaultTableModel model = (DefaultTableModel) newStatus.getModel();
        model.setRowCount(0); // Limpiar tabla

        Nodo<Proceso> aux = colaNuevo.Head; //vas a conseguir el primero de los nodos
        while (aux != null) { //mientras que no haya ningún proceso anteriormente... (carga inicial de procesos aleatorios)
            Proceso p = aux.getData(); //consigues la referencia del proceso p
            model.addRow(new Object[] {
                    p.getID(),
                    p.getPrioridad(),
                    p.getNombre(),
                    p.getMAR(),
                    p.getPC(),
                    p.getTiempoRestanteDeadline()
            });
            aux = aux.getNext();
        }
    }

    /**
     * USADO para debuggear como es que las clases instanciadas en main pueden
     * alterar el modo
     * 
     */
    private void PSWbuttonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PSWbuttonMouseClicked
        // Cambiar el PSW
        if (this.RTOSref.PSW == 0) {
            this.RTOSref.PSW = 1;
            // Cambiar a modo USUARIO
            modoU.setVisible(true);
            modoK.setVisible(false);
            PSWbutton.setText("Modo: USUARIO");
        } else {
            this.RTOSref.PSW = 0;
            // Cambiar a modo KERNEL
            modoU.setVisible(false);
            modoK.setVisible(true);
            PSWbutton.setText("Modo: KERNEL");
        }
    }// GEN-LAST:event_PSWbuttonMouseClicked

    private void PSWbuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PSWbuttonActionPerformed

    }// GEN-LAST:event_PSWbuttonActionPerformed

    public TabbedPaneCustom getGestionCargaTAB() {
        return GestionCargaTAB;
    }

    public void setGestionCargaTAB(TabbedPaneCustom GestionCargaTAB) {
        this.GestionCargaTAB = GestionCargaTAB;
    }

    public JButton getPSWbutton() {
        return PSWbutton;
    }

    public void setPSWbutton(JButton PSWbutton) {
        this.PSWbutton = PSWbutton;
    }

    public JLabel getTRDtext() {
        return TRDtext;
    }

    public void setTRDtext(JLabel TRDtext) {
        this.TRDtext = TRDtext;
    }

    public JTable getBlockedSStatus() {
        return blockedSStatus;
    }

    public void setBlockedSStatus(JTable blockedSStatus) {
        this.blockedSStatus = blockedSStatus;
    }

    public JTable getBlockedStatus() {
        return blockedStatus;
    }

    public void setBlockedStatus(JTable blockedStatus) {
        this.blockedStatus = blockedStatus;
    }

    public JTable getExitStatus() {
        return exitStatus;
    }

    public void setExitStatus(JTable exitStatus) {
        this.exitStatus = exitStatus;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public void setjPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public void setjScrollPane5(JScrollPane jScrollPane5) {
        this.jScrollPane5 = jScrollPane5;
    }

    public JScrollPane getjScrollPane6() {
        return jScrollPane6;
    }

    public void setjScrollPane6(JScrollPane jScrollPane6) {
        this.jScrollPane6 = jScrollPane6;
    }

    public JScrollPane getjScrollPane7() {
        return jScrollPane7;
    }

    public void setjScrollPane7(JScrollPane jScrollPane7) {
        this.jScrollPane7 = jScrollPane7;
    }

    public JScrollPane getjScrollPane8() {
        return jScrollPane8;
    }

    public void setjScrollPane8(JScrollPane jScrollPane8) {
        this.jScrollPane8 = jScrollPane8;
    }

    public JLabel getModoK() {
        return modoK;
    }

    public void setModoK(JLabel modoK) {
        this.modoK = modoK;
    }

    public JLabel getModoU() {
        return modoU;
    }

    public void setModoU(JLabel modoU) {
        this.modoU = modoU;
    }

    public JTable getNewStatus() {
        return newStatus;
    }

    public void setNewStatus(JTable newStatus) {
        this.newStatus = newStatus;
    }

    public JTextArea getOutputStreamConsole() {
        return outputStreamConsole;
    }

    public void setOutputStreamConsole(JTextArea outputStreamConsole) {
        this.outputStreamConsole = outputStreamConsole;
    }

    public JTable getReadySStatus() {
        return readySStatus;
    }

    public void setReadySStatus(JTable readySStatus) {
        this.readySStatus = readySStatus;
    }

    public JTable getReadyStatus() {
        return readyStatus;
    }

    public void setReadyStatus(JTable readyStatus) {
        this.readyStatus = readyStatus;
    }

    public JTable getRunningStatus() {
        return runningStatus;
    }

    public void setRunningStatus(JTable runningStatus) {
        this.runningStatus = runningStatus;
    }

    public JPanel getVistaGCProcesos() {
        return vistaGCProcesos;
    }

    public void setVistaGCProcesos(JPanel vistaGCProcesos) {
        this.vistaGCProcesos = vistaGCProcesos;
    }

    public JPanel getVistaMemoria() {
        return vistaMemoria;
    }

    public void setVistaMemoria(JPanel vistaMemoria) {
        this.vistaMemoria = vistaMemoria;
    }

    public JPanel getVistaMetricas() {
        return vistaMetricas;
    }

    public void setVistaMetricas(JPanel vistaMetricas) {
        this.vistaMetricas = vistaMetricas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> new Vista_1(null, null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.tabbed.TabbedPaneCustom GestionCargaTAB;
    private javax.swing.JButton PSWbutton;
    private javax.swing.JLabel TRDtext;
    private javax.swing.JTable blockedSStatus;
    private javax.swing.JTable blockedStatus;
    private javax.swing.JTable exitStatus;
    private javax.swing.JButton gen1;
    private javax.swing.JButton gen2;
    private javax.swing.JButton gen20;
    private javax.swing.JButton gen21;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel modoK;
    private javax.swing.JLabel modoU;
    private javax.swing.JTable newStatus;
    private javax.swing.JTextArea outputStreamConsole;
    private javax.swing.JTable readySStatus;
    private javax.swing.JTable readyStatus;
    private javax.swing.JTable runningStatus;
    private javax.swing.JPanel vistaGCProcesos;
    private javax.swing.JPanel vistaMemoria;
    private javax.swing.JPanel vistaMetricas;
    // End of variables declaration//GEN-END:variables
}
